apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-packages-config
data:
  # Rails Environment
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  
  # Application URLs
  APP_URL: "https://pakiety.edk.org.pl"
  PUBLIC_DONATION_URL: "https://wspieram.edk.org.pl"
  
  # Przelewy24 Configuration (non-sensitive)
  PRZELEWY24_MERCHANT_ID: "276306"
  PRZELEWY24_POS_ID: "276306"
  PRZELEWY24_SANDBOX: "false"
  PRZELEWY24_RETURN_URL: "https://wspieram.edk.org.pl/cegielka/sukces"
  PRZELEWY24_STATUS_URL: "https://wspieram.edk.org.pl/webhooks/przelewy24"
  
  # aPaczka Configuration (non-sensitive)
  APACZKA_APP_ID: "1924897_5GkLmyke1mmfHjvGbQeB1Uf3"
  APACZKA_SANDBOX: "false"
  
  # Email Configuration (non-sensitive)
  SMTP_ADDRESS: "smtp-mail.outlook.com"
  SMTP_PORT: "587"
  SMTP_DOMAIN: "edk.org.pl"
  SMTP_USER_NAME: "pakiety@edk.org.pl"
  SMTP_AUTHENTICATION: "login"
  SMTP_ENABLE_STARTTLS_AUTO: "true"
  LEADER_EMAIL_FROM: "pakiety@edk.org.pl"
